### ISSUE TITLE
pocketbase-vue-starter Template

### ISSUE THREAD

**Issue by MRSessions** [benallfree/awesome-pocketbase#12]
Hey there,

Wanted to throw my repo in the hat.

I have created a pocketbase-vue-starter template that uses PocketBase as a framework with Go migrations.

The default first time admin setup has redirected to use the vue-client admin setup page.

This repo can be used with PocketBase running somewhere else or by how it's setup in the repo. I have set it up for PocketBase to host the static files of the vue-client, and this can be run on a single Docker container for ease (hence the redirection options for PocketBase)

I created this last night, and have been updating today. There's still more I would like to add to it, but here's the repo: https://github.com/MRSessions/pocketbase-vue-starter

Title: pocketbase-vue-starter
Description: A starter template for using Vue/Vuetify with Pocketbase as a backend.

Thank you!

**Comment by benallfree** [comment]
@MRSessions sounds great! Would you please create a PR to add your contribution? Thank you so much!

**Comment by MRSessions** [comment]
Absolutely. I'll try and get one up this afternoon/evening.

**Comment by ASoldo** [comment]
> Hey there,
> 
> Wanted to throw my repo in the hat.
> 
> I have created a pocketbase-vue-starter template that uses PocketBase as a framework with Go migrations.
> 
> The default first time admin setup has redirected to use the vue-client admin setup page.
> 
> This repo can be used with PocketBase running somewhere else or by how it's setup in the repo. I have set it up for PocketBase to host the static files of the vue-client, and this can be run on a single Docker container for ease (hence the redirection options for PocketBase)
> 
> I created this last night, and have been updating today. There's still more I would like to add to it, but here's the repo: https://github.com/MRSessions/pocketbase-vue-starter
> 
> Title: pocketbase-vue-starter Description: A starter template for using Vue/Vuetify with Pocketbase as a backend.
> 
> Thank you!

Nuxt3 starter pack on it's way 😃? or should I do it? 🤨
