### ISSUE TITLE
Is possible to add an ORM in C#? (work in progress)

### ISSUE THREAD

**Issue by iluvadev** [benallfree/awesome-pocketbase#3]
Hi, I'm working in an ORM in c# for PocketBase: https://github.com/iluvadev/PocketBaseClient-csharp

It has a Code Generator to map PocketBase Collections to objects: generates also enums and maps relations to objects.

It is not finished yet, but I think it might be interesting for c# developers.

Main work left is finish CLI for Code Generator, queries and file processing (maybe also realtime support).

**Comment by benallfree** [comment]
Hi @iluvadev, sounds great! Please let me know when you’re ready for it to be posted.

**Comment by iluvadev** [comment]
Hi @benallfree, it could be posted. 
I publised a release of the project. It generates the code to operate with a concrete PocketBase Application, with a Filter system for queries.

File processing and realtime support is not yet implemented.

**Comment by benallfree** [comment]
Added
