### ISSUE TITLE
Docker images for pocketbase

### ISSUE THREAD

**Issue by kdpuvvadi** [benallfree/awesome-pocketbase#37]
Hi, 

I'm maintaining docker images for pocketbase url: https://github.com/kdpuvvadi/pocketbase. Mostly was doing this for my self but everyones welcome to use it. Builds are automated with actions and triggered by release. Releases are trigger from ansible playbook running in my homelab. Appreciate you adding this to the list.

**Comment by benallfree** [comment]
Thanks! Please submit a PR when you're ready to add to the list.
