### ISSUE TITLE
Broken link "Cloud Functions"

### ISSUE THREAD

**Issue by j-wil** [benallfree/awesome-pocketbase#6]
The link "[Cloud Functions](https://github.com/benallfree/pockethost/tree/master/packages/js-cloud-funcs)" under the section serverless functions is broken.

**Comment by benallfree** [comment]
Thanks for the report! I’ll get this fixed asap, it’s the victim of a refactoring.

**Comment by klerpi** [comment]
I was going to report this too

**Comment by benallfree** [comment]
Yep this got merged with the pockethost.io repo, sorry about that!
